### PR TITLE
#15 Add detekt 

### LINKED ISSUE #15: Add Ktlint / detekt
### 🔍️ Description

- describe the feature

  

### 📌 Tasks 

- [ ] task1
- [ ] task2
- [ ] task3

### PR DESCRIPTION
**Pull request by ows3090**
### 🎯 Related issue
- closed #15 

#### 🔍️ summary

- Add detekt, one of the static analysis tools
- we can use it by typing the word ".gradlew detekt" 

I want to discuss about some of disabled detekt rules.
- [WildcardImport](https://detekt.dev/docs/rules/style/#wildcardimport)
- [MagicNumber](https://detekt.dev/docs/rules/style/#magicnumber)

**I think we should add WhildcardImport and MagicNumber since it's very bothering if we don't add it. How do you think about it?**

#### 📌 tasks 

- [x] Add detekt plugin in project's build gradle file and libs.version.toml file
- [x] Revise some of detekt error
- [x] Add disable detekt rules like MagicNumber etc ..

### CODE REVIEW

**Review by junwooYeom — APPROVED** [review]
👍

**Comment by ghost** [comment]
I agree to disable WildcardImport and MagicNumber.

**Comment by Ddudduu** [comment]
I think we should add MagicNumber however, the documentation says `WildcardImport` should be replaced with importing specific classes. What do the others think? I prefer wildcard cause it's simple!

**Comment by ghost** [comment]
I also think wildcardimport is convenient and looks good. However, sometimes there are things with the same name and it is difficult to find them if an error occurs.

**Comment by ows3090** [comment]
I think so too.
I'll remove wildcardimport disabled rules. Thank you

**Comment by ows3090** [comment]
@lee989898 @Ddudduu @Lee-Jun-Young 
I revised now. Please review PR

**Review by Ddudduu — COMMENTED** [review]
LGTM 👍👍👏

**Review by ghost — APPROVED** [review]
LGTM

**Pull request merged**
