### PR TITLE
#3 Create Issue Template

### PR DESCRIPTION
**Pull request by Ddudduu**
### 🎯 Related issue

- Issue #3 

#### 🔍️ summary

- Create Issue Template

#### 📌 tasks 

- [x] Type1 : Feature
- [x] Type2 : Bug Report

### CODE REVIEW

**Review by ows3090 — APPROVED** [review]
LGTM

**Comment by Lee-Jun-Young** [comment]
LGTM 👍🏻

**Comment by lee989898** [comment]
LGTM

**Review by ghost — APPROVED** [review]
LGTM

**Review by Lee-Jun-Young — APPROVED** [review]

**Review by junwooYeom — APPROVED** [review]
👍

**Pull request merged**
