### PR TITLE
#2 Create Pull Request Template

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ows3090** [comment]
@lee989898 
What is the difference between Implementation details and implementation?
And I'm also curious about the difference between screenshots and gifs.

**Comment by ghost** [comment]
@ows3090 
1. There are implementation and tasks in Implementation detail. They are set
- In Implementation, for example
  - I add an image because of ...  
- In task, for example
  - add image
  - add library
2. Due to the nature of the picker library, I thought that screenshots alone might not be enough. 
In the case of animation, I thought gifs were good for expression.  
If a screenshot is sufficient, use a screenshot. If it is not sufficient, use a gifs.

**Comment by junwooYeom** [comment]
Then, I prefer summary/implementation than implementation/implementation detail. I will be a little confused. 
And I think we can put gifs in screenshot, no need to be a screenshot is a single table.

**Comment by ghost** [comment]
That's a good idea. I'll change it that way.

**Review by junwooYeom — APPROVED** [review]
👍

**Comment by ows3090** [comment]
@lee989898 
Is a label necessary?
We can set pull request label in the right side bar.

**Comment by ghost** [comment]
@ows3090
There was no label in junwoo's pull request, so I tried to follow it. But I think it would be better to remove the label in template and select it from the side so that we can find it by label later. I'll change it

**Review by ows3090 — APPROVED** [review]

**Pull request merged**
